ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TICKET_ESCALATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TICKET_SLA_BREACH';
ALTER TYPE "AuthTokenType" ADD VALUE IF NOT EXISTS 'PORTAL_ACCESS';

ALTER TABLE "Ticket"
  ADD COLUMN "escalationLevel" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "slaPausedAt" TIMESTAMP(3),
  ADD COLUMN "slaPausedMinutes" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "SupportQueue"
  ADD COLUMN "routingStrategy" TEXT NOT NULL DEFAULT 'ROUND_ROBIN',
  ADD COLUMN "businessHours" JSONB,
  ADD COLUMN "holidays" JSONB,
  ADD COLUMN "pauseStatuses" JSONB,
  ADD COLUMN "escalationPolicy" JSONB;
