import PptxGenJS from "pptxgenjs";
import { parseMarkdownDocument, pickDocumentHighlights } from "./shared.js";

function sectionSlideBody(section) {
  const lines = [];

  for (const paragraph of section.paragraphs.slice(0, 2)) {
    lines.push(paragraph);
  }

  for (const bullet of section.bullets.slice(0, 4)) {
    lines.push(`- ${bullet}`);
  }

  return lines.join("\n\n");
}

export async function renderPptxArtifact({ title, markdown }) {
  const documentModel = parseMarkdownDocument(markdown, title);
  const pptx = new PptxGenJS();
  const highlights = pickDocumentHighlights(documentModel, 4);

  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Hydria";
  pptx.company = "Hydria";
  pptx.subject = documentModel.title;
  pptx.title = documentModel.title;
  pptx.lang = "fr-FR";
  pptx.theme = {
    headFontFace: "Aptos Display",
    bodyFontFace: "Aptos"
  };

  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "0B1220" };
  titleSlide.addText(documentModel.title, {
    x: 0.6,
    y: 0.6,
    w: 11.6,
    h: 0.9,
    fontSize: 25,
    bold: true,
    color: "F8FAFC"
  });
  titleSlide.addText("Generated by Hydria", {
    x: 0.62,
    y: 1.55,
    w: 4,
    h: 0.3,
    fontSize: 11,
    color: "D8AD5E"
  });
  if (highlights.length) {
    titleSlide.addText(
      highlights.map((item) => `• ${item}`).join("\n"),
      {
        x: 0.8,
        y: 2.15,
        w: 11.1,
        h: 3.7,
        fontSize: 18,
        color: "E6EDF7",
        breakLine: false,
        valign: "mid",
        margin: 0.1
      }
    );
  }

  for (const section of documentModel.sections) {
    const slide = pptx.addSlide();
    slide.background = { color: "10192B" };
    slide.addText(section.heading, {
      x: 0.6,
      y: 0.55,
      w: 11.6,
      h: 0.6,
      fontSize: 22,
      bold: true,
      color: "F8FAFC"
    });
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.6,
      y: 1.25,
      w: 11.6,
      h: 5.4,
      line: { color: "23344F", pt: 1 },
      fill: { color: "111B2E", transparency: 3 },
      radius: 0.16
    });
    slide.addText(sectionSlideBody(section) || "No content available.", {
      x: 0.9,
      y: 1.55,
      w: 11.0,
      h: 4.8,
      fontSize: 16,
      color: "DCE7F4",
      valign: "top",
      margin: 0.08
    });
  }

  const buffer = await pptx.write({ outputType: "nodebuffer" });

  return {
    buffer,
    extension: "pptx",
    mimeType:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation"
  };
}
