import XLSX from "xlsx";
import { buildContentRows, parseMarkdownDocument } from "./shared.js";

export async function renderXlsxArtifact({ title, markdown, spec }) {
  const raw = String(markdown || "").trim();
  const looksLikeCsv =
    /\n/.test(raw) &&
    raw
      .split("\n")
      .slice(0, 5)
      .every((line) => line.includes(","));

  if (looksLikeCsv || spec?.documentType === "spreadsheet") {
    const rows = raw
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean)
      .map((line) => line.split(",").map((cell) => cell.replace(/^"|"$/g, "").trim()));
    const workbook = XLSX.utils.book_new();
    const contentSheet = XLSX.utils.aoa_to_sheet(rows);

    XLSX.utils.book_append_sheet(workbook, contentSheet, "Sheet1");

    const buffer = XLSX.write(workbook, {
      type: "buffer",
      bookType: "xlsx"
    });

    return {
      buffer,
      extension: "xlsx",
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    };
  }

  const documentModel = parseMarkdownDocument(markdown, title);
  const workbook = XLSX.utils.book_new();
  const rows = buildContentRows(documentModel);

  const overviewSheet = XLSX.utils.aoa_to_sheet([
    ["Title", documentModel.title],
    ["Document Type", spec?.documentType || "document"],
    ["Section Count", documentModel.sections.length],
    ["Generated By", "Hydria"]
  ]);
  const contentSheet = XLSX.utils.json_to_sheet(
    rows.map((row) => ({
      Order: row.order,
      Section: row.section,
      Kind: row.kind,
      Content: row.content
    }))
  );

  XLSX.utils.book_append_sheet(workbook, overviewSheet, "Overview");
  XLSX.utils.book_append_sheet(workbook, contentSheet, "Content");

  const buffer = XLSX.write(workbook, {
    type: "buffer",
    bookType: "xlsx"
  });

  return {
    buffer,
    extension: "xlsx",
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  };
}
